package com.example.demo.service;

public enum Permiso {
 // Clientes
 CLIENTES_CREAR,
 CLIENTES_LEER,
 CLIENTES_ACTUALIZAR,
 CLIENTES_ELIMINAR,

 // Pedidos
 PEDIDOS_CREAR,
 PEDIDOS_LEER,
 PEDIDOS_ACTUALIZAR,
 PEDIDOS_ELIMINAR,

 // Inventario
 INVENTARIO_CREAR,
 INVENTARIO_LEER,
 INVENTARIO_ACTUALIZAR,
 INVENTARIO_ELIMINAR,

 // Produccion
 PRODUCCION_LEER,
 PRODUCCION_ACTUALIZAR,

 // Decoracion
 DECORACION_LEER,
 DECORACION_ACTUALIZAR,

 // Entregas
 ENTREGAS_LEER,
 ENTREGAS_ACTUALIZAR,

 // Pagos
 PAGOS_CREAR,
 PAGOS_LEER,
 PAGOS_ACTUALIZAR,
 PAGOS_ELIMINAR,

 // Facturacion
 FACTURACION_CREAR,
 FACTURACION_LEER,

 // Personal (empleados)
 PERSONAL_CREAR,
 PERSONAL_LEER,
 PERSONAL_ACTUALIZAR,
 PERSONAL_ELIMINAR,

 // Capacitaciones
 CAPACITACIONES_CREAR,
 CAPACITACIONES_LEER,
 CAPACITACIONES_ACTUALIZAR,
 CAPACITACIONES_ELIMINAR,

 // Proveedores
 PROVEEDORES_LEER,
 PROVEEDORES_CREAR,
 PROVEEDORES_ACTUALIZAR,
 PROVEEDORES_ELIMINAR,

 // Reportes
 REPORTES_LEER,

 // Limpieza y Mantenimiento
 LIMPIEZA_CREAR,
 LIMPIEZA_LEER,
 MANTENIMIENTO_CREAR,
 MANTENIMIENTO_LEER,

 // Dashboard
 DASHBOARD_ADMIN_LEER,
 DASHBOARD_EMPLEADO_LEER,
 DASHBOARD_CLIENTE_LEER,

 // Mi Perfil
 PERFIL_LEER,
 PERFIL_ACTUALIZAR,

 // Chef's Box
 CHEFS_BOX_CREAR,
 CHEFS_BOX_LEER,
 CHEFS_BOX_ACTUALIZAR,
 CHEFS_BOX_ELIMINAR
}
